require("lsp.lsp_installer")
require("lsp.cmp")
require("lsp.handlers").setup()
require("lsp.rust-tool")
require("lsp.clangd-extensions")
require("lsp.autopairs")
require("lsp.comment")
require("lsp.lspsaga")
